# Generated by Django 5.1.5 on 2025-03-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='TimeTracking',
        ),
    ]
