# Generated by Django 5.1.5 on 2025-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0008_delete_announcement_delete_timetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager')], default='user', max_length=10),
        ),
    ]
